autenticacao/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'autenticacao'

urlpatterns = [
    path('index/', views.index_view, name="index"),
    path('registo/', views.registo_view, name="registo"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),

    # recuperação de password
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='registration/custom_password_reset_form.html'), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='registration/custom_password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/custom_password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/custom_password_reset_complete.html'), name='password_reset_complete'),
]

curso/urls.py
from django.urls import path

from . import views

app_name= 'curso'

urlpatterns = [
    path('curso/', views.curso_view, name="curso"),
    path('disciplina_curso/<int:curso_id>', views.disciplina_curso_view, name="disciplina_curso"),
    path('projeto/', views.projeto_view, name="projeto"),
    path('', views.inicio, name='inicio'),
    path('novo_curso/', views.novo_curso_view, name="novo_curso"),
    path('curso/<int:curso_id>/edita_curso', views.edita_curso_view,name="edita_curso"),
    path('curso/<int:curso_id>/apaga_curso', views.apaga_curso_view,name="apaga_curso"),
    path('detalhe_disciplina/<int:disciplina_id>',views.detalhes_disciplina_view, name= "detalhe_disciplina"),

    path('disciplina/<int:disciplina_id>/', views.disciplina_view, name="disciplina"),
    path('nova_disciplina/<int:curso_id>', views.nova_disciplina_view, name="nova_disciplina"),
    path('edita_disciplina/<int:disciplina_id>/', views.edita_disciplina_view, name='edita_disciplina'),
    path('apaga_disciplina/<int:disciplina_id>', views.apaga_disciplina_view,name="apaga_disciplina"),

    path('novo_projeto/<int:disciplina_id>', views.novo_projeto_view, name="novo_projeto"),
    path('edita_projeto/<int:projeto_id>', views.edita_projeto_view,name="edita_projeto"),
    path('apaga_projeto/<int:projeto_id>', views.apaga_projeto_view,name="apaga_projeto"),


]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),
    path('pwsite/', include('pwsite.urls')),
    path('guia_de_hobbies/', include('guia_de_hobbies.urls')),
    path('bandas/', include('bandas.urls')),
    path('curso/', include('curso.urls')),
    path('praias/', include('praias.urls')),
    path('autenticacao/', include('autenticacao.urls')),
    path('meteo/', include('meteo.urls')),
    path('', include('portfolio.urls')),
    path('artigos/',include('artigos.urls')),




]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

curso/models.py
from django.db import models

# Create your models here.

class Curso(models.Model):
    nome= models.CharField(max_length= 100)
    apresentacao= models.CharField(max_length= 500)
    objetivo= models.CharField(max_length= 255)
    competencia= models.CharField(max_length= 255)


    def __str__(self):
         return self.nome


class Area_cientifica(models.Model):
    nome= models.CharField(max_length= 100)

    def __str__(self):
        return self.nome


class Disciplina(models.Model):
    nome = models.CharField(max_length= 100)
    ano = models.IntegerField(default=None)
    semestre = models.CharField(max_length= 100)
    ects = models.IntegerField(default=None)
    curricularIUnitReadableCode= models.CharField(max_length= 255)
    areaCientifica= models.ForeignKey(Area_cientifica, on_delete=models.CASCADE)
    cursos = models.ManyToManyField(Curso, related_name="disciplinas")



    def __str__(self):
        return self.nome




class Projeto(models.Model):
    nome= models.CharField(max_length= 100)
    descricao= models.CharField(max_length= 255)
    conceitoAplicado= models.CharField(max_length= 255)
    tecnologiaUtilizada= models.CharField(max_length= 100)
    linkYoutube= models.URLField(blank=True)
    linkGitHub= models.URLField(blank=True)
    imagem= models.ImageField(upload_to="curso", null=True, blank=True, default=None)
    disciplinas = models.ManyToManyField(Disciplina, related_name="projetos")


    def __str__(self):
        return self.nome

class Linguagem(models.Model):
    nome= models.CharField(max_length= 100)
    disciplina= models.ManyToManyField(Disciplina )


    def __str__(self):
        return self.nome


class Docente(models.Model):
    nome = models.CharField(max_length=100)
    email = models.CharField(max_length=100, default='', blank=True)
    disciplinas = models.ManyToManyField(Disciplina, related_name="docentes")


    def __str__(self):

        return self.nome

curso/forms.py
from django import forms    # formulários Django
from .models import Curso
from .models import Disciplina
from .models import Projeto


class CursoForm(forms.ModelForm):
  class Meta:
    model = Curso
    fields = '__all__'



class DisciplinaForm(forms.ModelForm):
  class Meta:
    model = Disciplina
    fields = '__all__'


class ProjetoForm(forms.ModelForm):
  class Meta:
    model = Projeto
    fields = '__all__'

curso/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from .forms import CursoForm
from .forms import DisciplinaForm
from .forms import ProjetoForm
from .models import Curso
from .models import Disciplina
from .models import Projeto


# Create your views here.

from django.http import HttpResponse

def curso_view(request):
    context = {
        'cursos': Curso.objects.all().order_by('nome'),
    }
    return render(request, "curso/curso.html", context)


def inicio(request):
    context = {
        'cursos': Curso.objects.all().order_by('nome'),
    }
    return render(request, "curso/curso.html", context)


def disciplina_curso_view(request, curso_id):
    curso = Curso.objects.get(id=curso_id)
    disciplinas = curso.disciplina_set.all().order_by('nome')  # Obtém disciplinas associadas ao curso
    context = {
        'curso': curso,
        'disciplinas': disciplinas,
    }
    return render(request, "curso/disciplina_curso.html", context)


def projeto_view(request):
    context = {
        'projetos': Projeto.objects.all().order_by('nome'),
    }
    return render(request, "curso/projeto.html", context)

def detalhes_disciplina_view(request, disciplina_id):
    context= {
        'disciplina': Disciplina.objects.get(id=disciplina_id),
    }

    return render(request, 'curso/disciplina.html',context)


@login_required
def novo_curso_view(request):

    form = CursoForm(request.POST or None, request.FILES)

    if form.is_valid():
        form.save()
        return redirect('curso:curso')

    context = {'form': form}
    return render(request, 'curso/novo_curso.html', context)



@login_required
def edita_curso_view(request, curso_id):
    curso = Curso.objects.get(id=curso_id)

    if request.POST:
        form = CursoForm(request.POST or None, request.FILES, instance=curso)
        if form.is_valid():
            form.save()
            return redirect('curso:curso')
    else:
        form = CursoForm(instance=curso)

    context = {'form': form, 'curso':curso}
    return render(request, 'curso/edita_curso.html', context)




@login_required
def apaga_curso_view(request, curso_id):
    curso = Curso.objects.get(id=curso_id)
    curso.delete()
    return redirect('curso:curso')



@login_required
def nova_disciplina_view(request, curso_id):
    curso = Curso.objects.get(id=curso_id)
    form = DisciplinaForm(request.POST or None, request.FILES)

    if form.is_valid():
        disciplina = form.save(commit=False)
        disciplina.cursos = curso
        disciplina.save()
        return redirect('curso:disciplina')

    context = {'form': form, 'disciplina': disciplina}
    return render(request, 'curso/nova_disciplina.html', context)


@login_required
def edita_disciplina_view(request, disciplina_id):
    disciplina = Disciplina.objects.get(id=disciplina_id)

    if request.method == 'POST':
        form = DisciplinaForm(request.POST, request.FILES, instance=disciplina)
        if form.is_valid():
            form.save()
            return redirect('curso:disciplina', disciplina_id=disciplina.id)
    else:
        form = DisciplinaForm(instance=disciplina)

    context = {'form': form, 'disciplina': disciplina}
    return render(request, 'curso/edita_disciplina.html', context)



@login_required
def apaga_disciplina_view(request, disciplina_id):
    disciplina = Disciplina.objects.get(id=disciplina_id)
    disciplina.delete()
    return redirect('curso:disciplina')

@login_required
def disciplina_view(request, disciplina_id):
    disciplina = Disciplina.objects.get(id=disciplina_id)
    context = {'disciplina': disciplina}
    return render(request, 'curso/disciplina.html', context)



@login_required
def novo_projeto_view(request, disciplina_id):
    disciplina = Disciplina.objects.get(id=disciplina_id)
    form = ProjetoForm(request.POST or None, request.FILES)

    if form.is_valid():
        projeto = form.save(commit=False)
        projeto.disciplinas = disciplina
        disciplina.save()
        return redirect('curso:projeto')

    context = {'form': form}
    return render(request, 'curso/novo_projeto.html', context)



@login_required
def edita_projeto_view(request, projeto_id):
    projeto = Projeto.objects.get(id=projeto_id)

    if request.method == 'POST':
        form = ProjetoForm(request.POST, request.FILES, instance=projeto)
        if form.is_valid():
            form.save()
            # Corrigindo o redirecionamento para a visualização da disciplina
            return redirect('curso:disciplina', disciplina_id=projeto.disciplinas.first().id)
    else:
        form = ProjetoForm(instance=projeto)

    context = {'form': form, 'projeto': projeto}
    return render(request, 'curso/edita_projeto.html', context)




@login_required
def apaga_projeto_view(request, projeto_id):
    projeto = Projeto.objects.get(id=projeto_id)
    projeto.delete()
    return redirect('curso:projeto')

curso/templates/curso/curso.html
<!-- curso.html -->
{% extends 'curso/layout.html' %}

{% block content %}

{% for infocurso in cursos %}

    <h2>{{ infocurso.nome }}</h2>

    <h4>Apresentação do Curso</h4>
    <p>{{ infocurso.apresentacao }}</p>

    <h4>Objetivos do Curso</h4>
    <p>{{ infocurso.objetivo }}</p>

    <h4>Competências Desenvolvidas</h4>
    <p>{{ infocurso.competencia }}</p>

    <h4>Disciplinas:</h4>
    <ul>
        {% for disciplina in infocurso.disciplinas.all %}
            <li>
                <a href="{% url 'curso:detalhe_disciplina' disciplina.id %}">{{ disciplina.nome }}</a>
            </li>
        {% endfor %}
    </ul>

    <a href="{% url 'curso:edita_curso' infocurso.id %}">
        <button>Editar informação do curso</button>
    </a>


    <a href="{% url 'curso:apaga_curso' infocurso.id %}">
      <button>Apagar o curso</button>
    </a>


{%endfor%}

<p><a href="{% url 'curso:novo_curso' %}">
        <button>Inserir novo curso</button>
    </a></p>


{% endblock %}

curso/templates/curso/disciplina.html
{% extends 'curso/layout.html' %}

{% block content %}

    <h2>Detalhes da Disciplina</h2>

    <h3>{{ disciplina.nome }}</h3>
    <p>Ano: {{ disciplina.ano }}</p>
    <p>Semestre: {{ disciplina.semestre }}</p>
    <p>ECTS: {{ disciplina.ects }}</p>
    <p>Código: {{ disciplina.curricularIUnitReadableCode }}</p>
    <p>Área Científica: {{ disciplina.areaCientifica }}</p>



    <a href="{% url 'curso:edita_disciplina' disciplina.id %}">
        <button>Editar disciplina</button>
    </a>


    <a href="{% url 'curso:apaga_disciplina' disciplina.id %}">
      <button>Apaga a disciplina</button>
    </a>

    {% for disciplina in disciplinas%}

    <a href="{% url 'curso:nova_disciplina' disciplina.curso.id %}">
            <button>Inserir nova disciplina</button>
    </a>
    {%endfor%}
   <p> <a href="{% url 'curso:curso' %}">Voltar para a lista de cursos</a></p>

{% endblock %}

curso/templates/curso/edita_curso.html
{% extends 'curso/layout.html' %}

{% block content %}
    <h3>Edita Curso</h3>

    <form action="{% url 'curso:edita_curso' curso.id %}" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Guardar">
    </form>

    {% if user.is_authenticated %}
        {% for group in user.groups.all %}
            {% if group.name == 'editores_curso' %}
                <a href="{% url 'curso:curso' %}">
                    <button>Cancelar</button>
                </a>
            {% endif %}
        {% endfor %}
        <a href="{% url 'curso:apaga_curso' curso.id %}">
            <button>Apagar curso</button>
        </a>
    {% endif %}

    <button type="button" onclick="window.history.back()">Cancelar</button>

{% endblock %}

curso/templates/curso/edita_disciplina.html
{% extends 'curso/layout.html' %}

{% block content %}
    <h3>Edita Disciplina</h3>

    <form action="{% url 'curso:edita_disciplina' disciplina.id %}" method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Guardar">
    </form>

     {% if user.is_authenticated %}
        {% for group in user.groups.all %}
            {% if group.name == 'editores_curso' %}
                <a href="{% url 'curso:edita_disciplina' disciplina.id %}">
                    <button>Cancelar</button>
                </a>
            {% endif %}
        {% endfor %}

    {% endif %}

    <button type="button" onclick="window.history.back()">Cancelar</button>

{% endblock %}

curso/templates/curso/edita_projeto.html
{% extends 'curso/layout.html' %}

{% block content %}
    <h3>Edita Projeto</h3>

    <form action="{% url 'curso:edita_projeto' projeto.id %}" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Guardar">
    </form>

      {% if user.is_authenticated %}
        {% for group in user.groups.all %}
            {% if group.name == 'editores_curso' %}
                <a href="{% url 'curso:apaga_projeto' projeto.id %}">
                    <button>Cancelar</button>
                </a>
            {% endif %}
        {% endfor %}
    {% endif %}

      <button type="button" onclick="window.history.back()">Cancelar</button>

{% endblock %}

curso/templates/curso/layout.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Departamento de Engenharia Informática e Sistemas de Informação{% endblock %}</title>

    {% load static %}
        <p><a href="/"  target="_blank">Portfolio</a></p>

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/5d1319edfb.js" crossorigin="anonymous"></script>

    <!-- CSS Externo -->
    <link rel="stylesheet" href="{% static 'curso/estilo.css' %}">

    <!-- Bloco de Estilos Específicos -->
    <style>
        {% block style %}
        {% endblock %}
    </style>
</head>
<body>
    <header>
        <h1>DEISI - Departamento de Engenharia Informática e Sistemas de Informação</h1>
        <nav>
              {% if request.user.is_authenticated %}
                 <!---Username:{{request.user.username}}--->
                <a href="{% url 'autenticacao:logout' %}"><button>Logout</button></a>
                 {% else %}
                <a href="{% url 'autenticacao:login' %}"><button>Login</button></a>
                {% endif %}
            <ul>
                <li><a href="{% url 'curso:curso' %}">Curso</a></li>
                <li><a href="{% url 'curso:projeto' %}">Projeto</a></li>
                {% for disciplina in disciplinas %}
                <li><a href="{% url 'curso:disciplina_curso' disciplina.id %}">{{ disciplina.nome }}</a></li>
                {% endfor %}
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        &copy; Ana Salvador.
    </footer>
</body>
</html>

curso/templates/curso/nova_disciplina.html
{% extends 'curso/layout.html' %}

{% block content %}
    <h3>Nova disciplina</h3>

    <form action="" method="post" enctype='multipart/form-data'>
    <!-- enctype deve ser definido se houver submissão de ficheiros ou imagens -->

      {% csrf_token %}
      <table>
          {{ form }}
      </table>
      <input type="submit" value="Criar disciplina">

    </form>

{% endblock %}

curso/templates/curso/novo_curso.html
{% extends 'curso/layout.html' %}

{% block content %}
    <h3>Novo curso</h3>

    <form action="" method="post" enctype='multipart/form-data'>
    <!-- enctype deve ser definido se houver submissão de ficheiros ou imagens -->

      {% csrf_token %}
      <table>
          {{ form }}
      </table>
      <input type="submit" value="Criar curso">

    </form>

{% endblock %}

curso/templates/curso/novo_projeto.html
{% extends 'curso/layout.html' %}

{% block content %}
    <h3>Novo projeto</h3>

    <form action="" method="post" enctype='multipart/form-data'>
    <!-- enctype deve ser definido se houver submissão de ficheiros ou imagens -->

      {% csrf_token %}
      <table>
          {{ form }}
      </table>
      <input type="submit" value="Criar projeto">

    </form>

{% endblock %}

curso/templates/curso/projeto.html
<!-- projeto.html -->
{% extends 'curso/layout.html' %}

{% block content %}

{% for projeto in projetos %}

    <ul>
        {% for disciplina in projeto.disciplinas.all %}
            <h3>{{ disciplina.nome }}</h3>
       {% endfor %}
    </ul>
    <h5><li>{{ projeto.nome }}</li></h5>
    <p>Descrição: {{ projeto.descricao }}</p>
    <p>Conceitos Aplicados: {{ projeto.conceitoAplicado }}</p>
    <p>Tecnologias Utilizadas: {{ projeto.tecnologiaUtilizada }}</p>

    {% if projeto.imagem %}
        <img src="{{ projeto.imagem.url }}">
    {% endif %}

    <h5>Links</h5>
    <p>Vídeo no Youtube: <a href="{{ projeto.linkYoutube }}">{{ projeto.linkYoutube }}</a></p>
    <p>Repositório GitHub: <a href="{{ projeto.linkGitHub }}">{{ projeto.linkGitHub }}</a></p>

    <a href="{% url 'curso:edita_projeto' projeto.id %}">
                <button>Editar projeto</button>
    </a>

    {% if projeto.disciplinas and projeto.disciplinas.id %}
    <a href="{% url 'curso:novo_projeto' projeto.disciplinas.id %}">
        <button>Inserir novo projeto</button>
    </a>
    {% endif %}

     <a href="{% url 'curso:apaga_projeto' projeto.id %}">
      <button>Apaga projeto</button>
    </a>

{% endfor %}


{% endblock %}