autenticacao/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'autenticacao'

urlpatterns = [
    path('index/', views.index_view, name="index"),
    path('registo/', views.registo_view, name="registo"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),

    # recuperação de password
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='registration/custom_password_reset_form.html'), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='registration/custom_password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/custom_password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/custom_password_reset_complete.html'), name='password_reset_complete'),
]

bandas/urls.py
from django.urls import path
from . import views

app_name = 'bandas'

urlpatterns = [
    path('', views.index_view),
    path('bandas/<int:banda_id>/banda', views.banda_album_view, name="banda_album"),
    path('bandas/', views.bandas_view, name="bandas"),
    path('banda_album/<int:banda_id>/', views.banda_album_view, name="banda_album"),
    path('albuns/', views.index_view, name="albuns"),
    path('album/', views.albuns_view, name="album"),
    path('musicas/', views.musicas_view, name="musicas"),
    path('nova_banda/', views.nova_banda_view, name="nova_banda"),
    path('bandas/<int:banda_id>/edita_banda', views.edita_banda_view, name="edita_banda"),
    path('bandas/<int>banda_id>/apaga_banda', views.apaga_banda_view, name="apaga_banda"),
    path('novo_album/<int:banda_id>', views.novo_album_view, name="novo_album"),
    path('edita_album/<int:album_id>', views.edita_album_view, name="edita_album"),
    path('apaga_album/<int:album_id>', views.apaga_album_view, name="apaga_album"),
    path('nova_musica/<int:album_id>', views.nova_musica_view, name="nova_musica"),
    path('edita_musica/<int:musica_id>', views.edita_musica_view, name="edita_musica"),
    path('apaga_musica/<int:musica_id>', views.apaga_musica_view, name="apaga_musica"),
     path('musicas/<int:album_id>/', views.album_musicas_view, name="album_musicas"),  # Nova URL
]

curso/urls.py
from django.urls import path

from . import views

app_name= 'curso'

urlpatterns = [
    path('curso/', views.curso_view, name="curso"),
    path('disciplina_curso/<int:curso_id>', views.disciplina_curso_view, name="disciplina_curso"),
    path('projeto/', views.projeto_view, name="projeto"),
    path('', views.inicio, name='inicio'),
    path('novo_curso/', views.novo_curso_view, name="novo_curso"),
    path('curso/<int:curso_id>/edita_curso', views.edita_curso_view,name="edita_curso"),
    path('curso/<int:curso_id>/apaga_curso', views.apaga_curso_view,name="apaga_curso"),
    path('detalhe_disciplina/<int:disciplina_id>',views.detalhes_disciplina_view, name= "detalhe_disciplina"),

    path('disciplina/<int:disciplina_id>/', views.disciplina_view, name="disciplina"),
    path('nova_disciplina/<int:curso_id>', views.nova_disciplina_view, name="nova_disciplina"),
    path('edita_disciplina/<int:disciplina_id>/', views.edita_disciplina_view, name='edita_disciplina'),
    path('apaga_disciplina/<int:disciplina_id>', views.apaga_disciplina_view,name="apaga_disciplina"),

    path('novo_projeto/<int:disciplina_id>', views.novo_projeto_view, name="novo_projeto"),
    path('edita_projeto/<int:projeto_id>', views.edita_projeto_view,name="edita_projeto"),
    path('apaga_projeto/<int:projeto_id>', views.apaga_projeto_view,name="apaga_projeto"),


]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),
    path('pwsite/', include('pwsite.urls')),
    path('guia_de_hobbies/', include('guia_de_hobbies.urls')),
    path('bandas/', include('bandas.urls')),
    path('curso/', include('curso.urls')),
    path('praias/', include('praias.urls')),
    path('autenticacao/', include('autenticacao.urls')),
    path('meteo/', include('meteo.urls')),
    path('', include('portfolio.urls')),
    path('artigos/',include('artigos.urls')),




]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

bandas/models.py
from django.db import models

# Create your models here.

class Banda(models.Model):
    nome = models.CharField(max_length=255)
    foto = models.ImageField(upload_to="bandas/", null=True, blank=True, default=None)
    nacionalidade = models.CharField(max_length=255)
    ano_de_criacao = models.IntegerField(default=None)
    detalhe = models.CharField(max_length=255, null=True)
    biografia = models.TextField(default='', null=True, blank=True)

    def __str__(self):
        return self.nome

class Album(models.Model):
    banda = models.ForeignKey(Banda, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=100)
    capa = models.ImageField(upload_to="bandas", null=True, blank=True, default=None)
    #ficheiro = models.FileField(upload_to='bandas/ficheiros', null=True, blank=True)
    ano_lancamento = models.IntegerField(default=None)


    def __str__(self):
        return self.titulo

class Musica(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=255)
    data = models.DateField(auto_now_add=True)
    spotify_link = models.URLField(blank=True)
    duracao = models.DurationField()
    letra = models.TextField(default='', null=True, blank=True)
    biografia = models.TextField(default='', null=True, blank=True)

    def __str__(self):
        return self.titulo

bandas/forms.py
from django import forms    # formulários Django
from .models import Banda
from .models import Musica
from .models import Album


class BandaForm(forms.ModelForm):
    class Meta:
        model = Banda
        fields = '__all__'

        widgets = {
            'nome': forms.TextInput(attrs={'placeholder': 'Nome da banda', 'title': 'Insira o nome da banda.'}),
            'nacionalidade': forms.TextInput(attrs={'placeholder': 'Nacionalidade', 'title': 'Insira a nacionalidade da banda.'}),
            'ano_de_criacao': forms.NumberInput(attrs={'placeholder': 'Ano de Criação', 'title': 'Insira o ano de criação da banda.'}),
            'detalhe': forms.TextInput(attrs={'placeholder': 'Detalhe', 'title': 'Insira algum detalhe adicional sobre a banda.'}),
            'biografia': forms.Textarea(attrs={'placeholder': 'Biografia', 'title': 'Insira uma breve biografia da banda.'}),
        }

class MusicaForm(forms.ModelForm):
    class Meta:
        model = Musica
        fields = '__all__'

        widgets = {
            'titulo': forms.TextInput(attrs={'placeholder': 'Título da Música', 'title': 'Insira o título da música.'}),
            'data': forms.DateInput(attrs={'placeholder': 'Data de Lançamento', 'title': 'Insira a data de lançamento da música.'}),
            'spotify_link': forms.URLInput(attrs={'placeholder': 'Link do Spotify', 'title': 'Insira o link do Spotify da música (se disponível).'}),
            'duracao': forms.TextInput(attrs={'placeholder': 'Duração', 'title': 'Insira a duração da música.'}),
            'letra': forms.Textarea(attrs={'placeholder': 'Letra', 'title': 'Insira a letra da música (se disponível).'}),
            'biografia': forms.Textarea(attrs={'placeholder': 'Biografia Relacionada', 'title': 'Insira uma breve biografia relacionada à música (se disponível).'}),
        }

class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = '__all__'

        widgets = {
            'titulo': forms.TextInput(attrs={'placeholder': 'Título do Álbum', 'title': 'Insira o título do álbum.'}),
            'ano_lancamento': forms.NumberInput(attrs={'placeholder': 'Ano de Lançamento', 'title': 'Insira o ano de lançamento do álbum.'}),
        }

bandas/views.py
from django.shortcuts import render
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from .forms import BandaForm
from .forms import MusicaForm
from .forms import AlbumForm
from .models import Banda
from .models import Musica
from .models import Album

# Create your views here.

from django.http import HttpResponse

def index_view(request):
    context = {
        'bandas': Banda.objects.all().order_by('nome')
    }
    return render(request, "bandas/bandas.html", context)


def bandas_view(request):
    context = {
        'bandas': Banda.objects.all().order_by('nome')
    }
    return render(request, "bandas/bandas.html", context)

def banda_album_view(request, banda_id):
    context = {
        'banda': Banda.objects.get(id=banda_id),
        'albuns': Album.objects.filter(banda_id=banda_id),
    }
    return render(request, "bandas/banda_album.html", context)

def musicas_view(request):
    context = {
        'musicas': Musica.objects.all(),
    }
    return render(request, "bandas/musicas.html", context)

def albuns_view(request):
    context = {
        'album': Album.objects.all(),
    }
    return render(request, "bandas/albuns.html", context)

@login_required
@user_passes_test(lambda user: user.groups.filter(name='editores_bandas').exists())
def nova_banda_view(request):
    form = BandaForm(request.POST or None, request.FILES)
    if form.is_valid():
        form.save()
        return redirect('bandas:albuns')
    context = {'form': form}
    return render(request, 'bandas/nova_banda.html', context)

@login_required
def edita_banda_view(request, banda_id):
    banda = Banda.objects.get(id=banda_id)
    if request.POST:
        form = BandaForm(request.POST or None, request.FILES, instance=banda)
        if form.is_valid():
            form.save()
            return redirect('bandas:banda', banda_id=banda.id)
    else:
        form = BandaForm(instance=banda)
    context = {'form': form, 'banda': banda}
    return render(request, 'bandas/edita_banda.html', context)

@login_required
def apaga_banda_view(request, banda_id):
    banda = Banda.objects.get(id=banda_id)
    banda.delete()
    return redirect('bandas:bandas')

@login_required
@user_passes_test(lambda user: user.groups.filter(name='editores_bandas').exists())
def novo_album_view(request, banda_id):
    banda = Banda.objects.get(id=banda_id)
    form = AlbumForm(request.POST or None, request.FILES)
    if form.is_valid():
        album = form.save(commit=False)
        album.banda = banda
        album.save()
        return redirect('bandas:albuns')
    context = {'form': form}
    return render(request, 'bandas/novo_album.html', context)

@login_required
def edita_album_view(request, album_id):
    album = Album.objects.get(id=album_id)
    if request.method == 'POST':
        form = AlbumForm(request.POST, request.FILES, instance=album)
        if form.is_valid():
            form.save()
            return redirect('bandas:albuns', banda_id=album.banda.id)
    else:
        form = AlbumForm(instance=album)
    context = {'form': form, 'album': album}
    return render(request, 'bandas/edita_album.html', context)

@login_required
def apaga_album_view(request, album_id):
    album = Album.objects.get(id=album_id)
    album.delete()
    return redirect('bandas:albuns')

@login_required
@user_passes_test(lambda user: user.groups.filter(name='editores_bandas').exists())
def nova_musica_view(request, album_id):
    album = Album.objects.get(id=album_id)
    form = MusicaForm(request.POST or None, request.FILES)
    if form.is_valid():
        musica = form.save(commit=False)
        musica.album = album
        musica.save()
        return redirect('bandas:musicas')
    context = {'form': form}
    return render(request, 'bandas/nova_musica.html', context)

@login_required
def edita_musica_view(request, musica_id):
    musica = Musica.objects.get(id=musica_id)
    if request.method == 'POST':
        form = MusicaForm(request.POST, instance=musica)
        if form.is_valid():
            form.save()
            return redirect('bandas:musicas')
    else:
        form = MusicaForm(instance=musica)
    context = {'form': form, 'musica': musica}
    return render(request, 'bandas/edita_musica.html', context)

@login_required
def apaga_musica_view(request, musica_id):
    musica = Musica.objects.get(id=musica_id)
    musica.delete()
    return redirect('bandas:musicas')



def album_musicas_view(request, album_id):
    album = get_object_or_404(Album, id=album_id)
    musicas = Musica.objects.filter(album=album)
    context = {
        'album': album,
        'musicas': musicas,
    }
    return render(request, 'bandas/musicas.html', context)

bandas/templates/bandas/albuns.html
{% extends 'bandas/layout.html' %}

{% block content %}
<nav>
    <a href="{% url 'bandas:bandas' %}">Bandas</a>
</nav>

{% for album in albuns %}
    <h4>Título: {{ album.titulo }}</h4>

    {% if album.capa %}
        <img src="{{ album.capa.url }}" >
    {% endif %}

    <p>Banda: {{ album.banda.nome }}</p>
    <p>Ano de lançamento: {{ album.ano_lancamento }}</p>

    <P><a href="{% url 'bandas:album_musicas' album.id %}">
        Ver músicas deste álbum
    </a></P>

    <P><a href="{% url 'bandas:novo_album' album.banda.id %}">
        <button>Inserir novo álbum</button>
    </a></P>

    <a href="{% url 'bandas:edita_album' album.id %}">
        <button>Editar informação do álbum</button>
    </a>

    <a href="{% url 'bandas:apaga_album' album.id %}" onclick="return confirm('Tem certeza que deseja apagar este álbum?');">
        <button>Apagar álbum</button>
    </a>





{% endfor %}

{% endblock %}

bandas/templates/bandas/banda_album.html
{% extends 'bandas/layout.html' %}

{% block content %}
<nav>
    <a href="{% url 'bandas:bandas' %}">Bandas</a>
</nav>

{% for album in albuns %}
    <h4>Título: {{ album.titulo }}</h4>

    {% if album.capa %}
        <img src="{{ album.capa.url }}" >
    {% endif %}

    <p>Banda: {{ album.banda.nome }}</p>
    <p>Ano de lançamento: {{ album.ano_lancamento }}</p>

    <P><a href="{% url 'bandas:album_musicas' album.id %}">
        Ver músicas deste álbum
    </a></P>

    <P><a href="{% url 'bandas:novo_album' album.banda.id %}">
        <button>Inserir novo álbum</button>
    </a></P>

    <a href="{% url 'bandas:edita_album' album.id %}">
        <button>Editar informação do álbum</button>
    </a>

    <a href="{% url 'bandas:apaga_album' album.id %}" onclick="return confirm('Tem certeza que deseja apagar este álbum?');">
        <button>Apagar álbum</button>
    </a>





{% endfor %}

{% endblock %}

bandas/templates/bandas/bandas.html
{% extends 'bandas/layout.html' %}
{% block content %}
{% for banda in bandas %}
    {% load static %}
    {% if banda.foto %}
        <img src="{{ banda.foto.url }}" alt="Foto da banda">
    {% endif %}

    <h3>{{ banda.nome }}</h3>
    <p>Nacionalidade: {{ banda.nacionalidade }}</p>
    <p>Biografia: {{ banda.biografia }}</p>
    <p>Ano de criação: {{ banda.ano_de_criacao }}</p>
    <p>Álbum da banda <a href="{% url 'bandas:banda_album' banda.id %}">{{ banda.nome }}</a></p>
    <a href="{% url 'bandas:edita_banda' banda.id %}">
        <button>Editar informação da banda</button>
    </a>
    <a href="{% url 'bandas:apaga_banda' banda.id %}">
        <button>Apagar a banda</button>
    </a>
{% endfor %}
<p><a href="{% url 'bandas:nova_banda' %}">
    <button>Inserir nova banda</button>
</a></p>
{% endblock %}

bandas/templates/bandas/edita_album.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <h3>Edita Álbum</h3>

    <form action="{% url 'bandas:edita_album' album.id %}" method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Guardar">
    </form>

    {% if user.is_authenticated %}
        {% for group in user.groups.all %}
            {% if group.name == 'editores_bandas' %}
                <a href="{% url 'bandas:banda_album' album.banda.id %}">
                    <button>Cancelar</button>
                </a>
            {% endif %}
        {% endfor %}
    {% endif %}

    <button type="button" onclick="window.history.back()">Cancelar</button>
{% endblock %}

bandas/templates/bandas/edita_banda.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <h3>Edita Banda</h3>

    <form action="{% url 'bandas:edita_banda' banda.id %}" method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Guardar">
    </form>

    {% if user.is_authenticated %}
        {% for group in user.groups.all %}
            {% if group.name == 'editores_bandas' %}
                <a href="{% url 'bandas:banda' banda.id %}">
                    <button>Cancelar</button>
                </a>
            {% endif %}
        {% endfor %}
        <a href="{% url 'bandas:apaga_banda' banda.id %}">
            <button>Apagar banda</button>
        </a>
    {% endif %}

    <button type="button" onclick="window.history.back()">Cancelar</button>

{% endblock %}

bandas/templates/bandas/edita_musica.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <h3>Edita Música</h3>

    <form action="{% url 'bandas:edita_musica' musica.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>

    {% if user.is_authenticated %}
        {% for group in user.groups.all %}
            {% if group.name == 'editores_bandas' %}
                <a href="{% url 'bandas:banda' musica.album.banda.id %}">
                    <button>Cancelar</button>
                </a>
            {% endif %}
        {% endfor %}
        <a href="{% url 'bandas:apaga_musica' musica.id %}">
            <button>Apagar Música</button>
        </a>
    {% endif %}

    <button type="button" onclick="window.history.back()">Cancelar</button>
{% endblock %}

bandas/templates/bandas/html5-css.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Seletores CSS e Combinadores</title>
    <!-- Google Icons -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <style>
        /* Estilos adicionais aqui, se necessário */
    </style>
</head>
<body>
    <h3>Seletores CSS</h3>
    <p>O CSS (Cascading Style Sheets) é uma linguagem de estilo utilizada para descrever a apresentação de um documento HTML. Ela define como os elementos HTML devem ser exibidos na tela, no papel ou em outras mídias.</p>
    <table>
        <thead>
            <tr>
                <th>Seletores CSS</th>
                <th>Utilizado</th>
                <th>Comentário</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Seletor de elemento (tag)</td>
                <td><i class="material-icons">done</i></td>
                <td>Seleciona elementos HTML pelo nome da tag. Utilizado para estilizar todas as instâncias de uma tag específica. <a href="exemplo.html">Exemplo</a></td>
            </tr>
            <tr>
                <td>Seletor de classe (.)</td>
                <td><i class="material-icons">done</i></td>
                <td>Seleciona elementos HTML pela classe. Utilizado para estilizar elementos com a mesma classe. <a href="exemplo.html">Exemplo</a></td>
            </tr>
            <tr>
                <td>Seletor de ID (#)</td>
                <td><i class="material-icons">done</i></td>
                <td>Seleciona um único elemento HTML pelo ID. Utilizado para estilizar elementos únicos. <a href="exemplo.html">Exemplo</a></td>
            </tr>
            <!-- Adicione mais linhas conforme necessário -->
        </tbody>
    </table>

    <h3>Combinadores de seletores</h3>
    <table>
        <thead>
            <tr>
                <th>Combinadores</th>
                <th>Utilizado</th>
                <th>Comentário</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Espaço ( )</td>
                <td><i class="material-icons">done</i></td>
                <td>Seleciona elementos que são filhos de outro elemento. Utilizado para estilizar elementos específicos dentro de um contêiner. <a href="exemplo.html">Exemplo</a></td>
            </tr>
            <tr>
                <td>Combinador filho (>)</td>
                <td><i class="material-icons">done</i></td>
                <td>Seleciona elementos que são filhos diretos de outro elemento. Utilizado para estilizar elementos imediatamente dentro de um contêiner. <a href="exemplo.html">Exemplo</a></td>
            </tr>
            <tr>
                <td>Combinador de irmão adjacente (+)</td>
                <td><i class="material-icons">done</i></td>
                <td>Seleciona o próximo elemento irmão diretamente após o primeiro elemento. Utilizado para estilizar um elemento que segue imediatamente outro elemento. <a href="exemplo.html">Exemplo</a></td>
            </tr>
            <!-- Adicione mais linhas conforme necessário -->
        </tbody>
    </table>
</body>
</html>

bandas/templates/bandas/index.html
{% extends 'bandas/layout.html' %}


{% block content %}

<h1>BEM VINDO AS MINHAS BANDAS!</h1>

{% endblock %}

bandas/templates/bandas/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Bandas</title>
    {% load static %}
        <p><a href="/"  target="_blank">Portfolio</a></p>

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/5d1319edfb.js" crossorigin="anonymous"></script>

    <!-- CSS Externo -->
    <link rel="stylesheet" href="{% static 'bandas/estilos.css' %}">

    <!-- Bloco de Estilos Específicos -->
    <style>
        {% block style %}
        {% endblock %}
    </style>
</head>
<body>
    <header>
        <h1>Bandas Musicais</h1>
    </header>

    <nav>

        {% if request.user.is_authenticated %}
            Username:{{request.user.username}}
            <a href="{% url 'autenticacao:logout' %}"><button>Logout</button></a>
        {% else %}
            <a href="{% url 'autenticacao:login' %}"><button>Login</button></a>
        {% endif %}

    </nav>

    <main>
        {% block content %}
        {% endblock %}
    </main>



</body>
</html>

bandas/templates/bandas/musicas.html
{% extends 'bandas/layout.html' %}


{% block content %}

<nav>
    <a href="{% url 'bandas:albuns' %}">Album</a>
</nav>

{% for musica in musicas %}
    <h3>{{ musica.titulo }}</h3>
    <p> Álbum: {{ musica.album }}</p>
    <p> Data de lançamento: {{ musica.data }}</p>
    <p> Duração: {{ musica.duracao }}</p>
    {% if musica.letra %}
        <p>Letra:</p>
        <p>{{ musica.letra }}</p>
    {% endif %}
    <p> Biografia: {{ musica.biografia }}</p>
        {% if musica.spotify_link %}
        <p> Spotify: <a href="{{ musica.spotify_link }}">Ouça no Spotify</a></p>
    {% endif %}

    <P><a href="{% url 'bandas:nova_musica' musica.album.id %}">
        <button>Inserir nova musica</button>
    </a></P>

        <a href="{% url 'bandas:edita_musica' musica.id %}">
                <button>Editar informação da musica</button>
            </a>


     <a href="{% url 'bandas:apaga_musica' musica.id %}">
      <button>Apaga a musica</button>
    </a>
    {% endfor %}




{% endblock %}

bandas/templates/bandas/nova_banda.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <h3>Nova Banda</h3>

    <form action="" method="post" enctype='multipart/form-data'>
    <!-- enctype deve ser definido se houver submissão de ficheiros ou imagens -->

      {% csrf_token %}   <!-- obrigatório nos forms Django -->
      <table>
          {{ form }}   <!-- insere input para cada atributo da classebanda, numa tabela -->
      </table>
      <input type="submit" value="Criar banda">

    </form>

{% endblock %}

bandas/templates/bandas/nova_musica.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <h3>Nova Musica</h3>


    <form action="" method="post" enctype='multipart/form-data'>
    <!-- enctype deve ser definido se houver submissão de ficheiros ou imagens -->

      {% csrf_token %}   <!-- obrigatório nos forms Django -->
      <table>
          {{ form }}
      </table>
      <input type="submit" value="Criar musica">
    </form>


{% endblock %}

bandas/templates/bandas/novo_album.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <h3>Novo Album</h3>


    <form action="" method="post" enctype='multipart/form-data'>
    <!-- enctype deve ser definido se houver submissão de ficheiros ou imagens -->

      {% csrf_token %}   <!-- obrigatório nos forms Django -->
      <table>
          {{ form }}   <!-- insere input para cada atributo da classebanda, numa tabela -->
      </table>
      <input type="submit" value="Criar album">
    </form>

{% endblock %}