autenticacao/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'autenticacao'

urlpatterns = [
    path('index/', views.index_view, name="index"),
    path('registo/', views.registo_view, name="registo"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),

    # recuperação de password
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='registration/custom_password_reset_form.html'), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='registration/custom_password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/custom_password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/custom_password_reset_complete.html'), name='password_reset_complete'),
]

bandas/urls.py
from django.urls import path
from . import views

app_name = 'bandas'

urlpatterns = [
    path('', views.index_view),
    path('bandas/<int:banda_id>/banda', views.banda_album_view, name="banda_album"),
    path('bandas/', views.bandas_view, name="bandas"),
    path('banda_album/<int:banda_id>/', views.banda_album_view, name="banda_album"),
    path('albuns/', views.index_view, name="albuns"),
    path('album/', views.albuns_view, name="album"),
    path('musicas/', views.musicas_view, name="musicas"),
    path('nova_banda/', views.nova_banda_view, name="nova_banda"),
    path('bandas/<int:banda_id>/edita_banda', views.edita_banda_view, name="edita_banda"),
    path('bandas/<int>banda_id>/apaga_banda', views.apaga_banda_view, name="apaga_banda"),
    path('novo_album/<int:banda_id>', views.novo_album_view, name="novo_album"),
    path('edita_album/<int:album_id>', views.edita_album_view, name="edita_album"),
    path('apaga_album/<int:album_id>', views.apaga_album_view, name="apaga_album"),
    path('nova_musica/<int:album_id>', views.nova_musica_view, name="nova_musica"),
    path('edita_musica/<int:musica_id>', views.edita_musica_view, name="edita_musica"),
    path('apaga_musica/<int:musica_id>', views.apaga_musica_view, name="apaga_musica"),
     path('musicas/<int:album_id>/', views.album_musicas_view, name="album_musicas"),  # Nova URL
]

curso/urls.py
from django.urls import path

from . import views

app_name= 'curso'

urlpatterns = [
    path('curso/', views.curso_view, name="curso"),
    path('disciplina_curso/<int:curso_id>', views.disciplina_curso_view, name="disciplina_curso"),
    path('projeto/', views.projeto_view, name="projeto"),
    path('', views.inicio, name='inicio'),
    path('novo_curso/', views.novo_curso_view, name="novo_curso"),
    path('curso/<int:curso_id>/edita_curso', views.edita_curso_view,name="edita_curso"),
    path('curso/<int:curso_id>/apaga_curso', views.apaga_curso_view,name="apaga_curso"),
    path('detalhe_disciplina/<int:disciplina_id>',views.detalhes_disciplina_view, name= "detalhe_disciplina"),

    path('disciplina/<int:disciplina_id>/', views.disciplina_view, name="disciplina"),
    path('nova_disciplina/<int:curso_id>', views.nova_disciplina_view, name="nova_disciplina"),
    path('edita_disciplina/<int:disciplina_id>/', views.edita_disciplina_view, name='edita_disciplina'),
    path('apaga_disciplina/<int:disciplina_id>', views.apaga_disciplina_view,name="apaga_disciplina"),

    path('novo_projeto/<int:disciplina_id>', views.novo_projeto_view, name="novo_projeto"),
    path('edita_projeto/<int:projeto_id>', views.edita_projeto_view,name="edita_projeto"),
    path('apaga_projeto/<int:projeto_id>', views.apaga_projeto_view,name="apaga_projeto"),


]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),
    path('pwsite/', include('pwsite.urls')),
    path('guia_de_hobbies/', include('guia_de_hobbies.urls')),
    path('bandas/', include('bandas.urls')),
    path('curso/', include('curso.urls')),
    path('praias/', include('praias.urls')),
    path('autenticacao/', include('autenticacao.urls')),
    path('meteo/', include('meteo.urls')),
    path('', include('portfolio.urls')),
    path('artigos/',include('artigos.urls')),




]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

autenticacao/models.py
from django.db import models

# Create your models here.

autenticacao/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import models, authenticate, login, logout


def registo_view(request):
    if request.method == "POST":
        models.User.objects.create_user(
            username=request.POST['username'],
            email=request.POST['email'],
            first_name=request.POST['nome'],
            last_name=request.POST['apelido'],
            password=request.POST['password']
        )
        return redirect('login')

    return render(request, 'autenticacao/registo.html')


def login_view(request):
    if request.method == "POST":

        # Verifica as credenciais
        user = authenticate(
            request,
            username=request.POST['username'],
            password=request.POST['password']
        )
        if user:
            # Se as credenciais são válidas, faz login e redireciona
            login(request, user)
            return render(request, 'autenticacao/index.html')
        else:
            # Se inválidas, reenvia para login com mensagem
            render(request, 'autenticacao/login.html', {
                'mensagem':'Credenciais inválidas'
            })

    return render(request, 'autenticacao/login.html')


def logout_view(request):
    logout(request)
    return redirect('autenticacao:index')


def index_view(request):
    return render(request, 'autenticacao/index.html')

autenticacao/templates/autenticacao/index.html
<!DOCTYPE html>

<html>
<head>

</head>
<body>
    <header>
        <h1>Seja bem-vindo!</h1>
        <h4>Escolha uma aplicação</h4>
    </header>

    <nav>
        {% if request.user.is_authenticated %}
                Username: {{ request.user.username }}
                <a href="{% url 'autenticacao:logout' %}"><button>Logout</button></a>
            {% else %}
                <a href="{% url 'autenticacao:login' %}"><button>Login</button></a>
            {% endif %}

        <a href="{% url 'bandas:bandas' %}">BANDAS</a>
        <a href="{% url 'curso:curso' %}">CURSO</a>

    </nav>

    <main>
        {% block content %}
        {% endblock %}
    </main>



</body>
</html>

autenticacao/templates/autenticacao/layout.html
<head>
    <meta charset="UTF-8">
    <titulo>Autenticacao</titulo>
    {% load static %}

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/5d1319edfb.js" crossorigin="anonymous"></script>

    <!-- CSS Externo -->
    <link rel="stylesheet" href="{% static 'autenticacao/estilos.css' %}">

    <!-- Bloco de Estilos Específicos -->
    <style>
        {% block style %}
        {% endblock %}
    </style>
</head>
<body>
    <main>
            {% block content %}
            {% endblock %}
        </main>
</body>

autenticacao/templates/autenticacao/login.html
{%extends 'autenticacao/layout.html'%}

{% block content %}
    <h3>Login</h3>

    {% if mensagem %}
      <p>mensagem: {{ mensagem }}</p>
    {% endif %}

    <!-- formulário que pede as credenciais
    e as reenvia para a view 'login'. -->

    <form action="{% url 'autenticacao:login' %}" method="post">
      {% csrf_token %}
      <input type="text" name="username" placeholder="Username..">
      <input type="password" name="password" placeholder="Palavra-chave..">
      <input type="submit">
    </form>

    <a href="{% url 'autenticacao:registo' %}">
      <button>Registar</button>
    </a>

    <a href="{% url 'autenticacao:reset_password' %}">
      <button>Recuperar Palavra-chave</button>
    </a>

{% endblock %}

autenticacao/templates/autenticacao/registo.html
{%extends 'autenticacao/layout.html'%}

{% block content %}
    <h3>Registo</h3>

    <form action="{% url 'autenticacao:registo' %}" method="post">
      {% csrf_token %}
      <input type="text" name="username" placeholder="O seu username..">
      <input type="text" name="nome" placeholder="O seu nome..">
      <input type="text" name="apelido" placeholder="O seu apelido..">
      <input type="email" name="email" placeholder="O seu email..">
      <input type="password" name="password" placeholder="Defina a sua Palavra-chave..">
      <input type="submit" value="Criar">
    </form>

    <a href="{% url 'autenticacao:login' %}">Cancelar</a>

{% endblock %}

autenticacao/templates/autenticacao/user.html
{%extends 'autenticacao/layout.html'%}

{% block content %}

    <h3>Bem vido, {{request.user.first_name}} {{request.user.last_name}}</h3>

    <ul>
      <li>Username: {{request.user.username}}</li>
      <li>Email: {{request.user.email}}</li>
    </ul>

    <a href="{% url 'autenticacao:logout' %}">Logout</a>

  <h3>Suas aplicações:</h3>
    <u>
    <a href="{% url 'bandas:bandas' %}">Bandas</a>
    </u>
    <br>

    <u>
    <a href="{% url 'curso:curso' %}">Curso</a>
    </u>
    <br>

    <u>
    <a href="{% url 'artigo:artigo' %}">Artigos</a>
    </u>

{% endblock %}