curso/urls.py
from django.urls import path

from . import views

app_name= 'curso'

urlpatterns = [
    path('curso/', views.curso_view, name="curso"),
    path('disciplina_curso/<int:curso_id>', views.disciplina_curso_view, name="disciplina_curso"),
    path('projeto/', views.projeto_view, name="projeto"),
    path('', views.inicio, name='inicio'),
    path('novo_curso/', views.novo_curso_view, name="novo_curso"),
    path('curso/<int:curso_id>/edita_curso', views.edita_curso_view,name="edita_curso"),
    path('curso/<int:curso_id>/apaga_curso', views.apaga_curso_view,name="apaga_curso"),
    path('detalhe_disciplina/<int:disciplina_id>',views.detalhes_disciplina_view, name= "detalhe_disciplina"),

    path('disciplina/<int:disciplina_id>/', views.disciplina_view, name="disciplina"),
    path('nova_disciplina/<int:curso_id>', views.nova_disciplina_view, name="nova_disciplina"),
    path('edita_disciplina/<int:disciplina_id>/', views.edita_disciplina_view, name='edita_disciplina'),
    path('apaga_disciplina/<int:disciplina_id>', views.apaga_disciplina_view,name="apaga_disciplina"),

    path('novo_projeto/<int:disciplina_id>', views.novo_projeto_view, name="novo_projeto"),
    path('edita_projeto/<int:projeto_id>', views.edita_projeto_view,name="edita_projeto"),
    path('apaga_projeto/<int:projeto_id>', views.apaga_projeto_view,name="apaga_projeto"),


]

guia_de_hobbies/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views

app_name = 'guia_de_hobbies'

urlpatterns = [
    path('hobbies/', views.hobbies_view, name='hobbies'),
    path('hobbies_criancas/', views.hobbies_criancas_view, name='hobbies_criancas'),
    path('hobbies_adolescentes/', views.hobbies_adolescentes_view, name='hobbies_adolescentes'),
    path('hobbies_jovens/', views.hobbies_jovens_view, name='hobbies_jovens'),
    path('hobbies_idosos/', views.hobbies_idosos_view, name='hobbies_idosos'),
    ]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),
    path('pwsite/', include('pwsite.urls')),
    path('guia_de_hobbies/', include('guia_de_hobbies.urls')),
    path('bandas/', include('bandas.urls')),
    path('curso/', include('curso.urls')),
    path('praias/', include('praias.urls')),
    path('autenticacao/', include('autenticacao.urls')),
    path('meteo/', include('meteo.urls')),
    path('', include('portfolio.urls')),
    path('artigos/',include('artigos.urls')),




]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

guia_de_hobbies/models.py
from django.db import models

# Create your models here.

guia_de_hobbies/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse


def hobbies_view(request):
    return render(request, "hobbies/hobbies.html")

def hobbies_criancas_view(request):
    return render(request, "hobbies/hobbies_criancas.html")

def hobbies_adolescentes_view(request):
    return render(request, "hobbies/hobbies_adolescentes.html")

def hobbies_jovens_view(request):
    return render(request, "hobbies/hobbies_jovens.html")


def hobbies_idosos_view(request):
    return render(request, "hobbies/hobbies_idosos.html")

guia_de_hobbies/templates/hobbies/hobbies.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sugestões para hobbies</title>

    <h1>Escolhe da pirâmide etária a faixa que desejas conhecer sugestões de hobbies:</h1>

    <nav>
    <a href="{% url 'guia_de_hobbies:hobbies_criancas' %}">CRIANÇAS</a>
    </nav>

    <nav>
    <a href="{% url 'guia_de_hobbies:hobbies_adolescentes' %}">ADOLESCENTES</a>
    </nav>

    <nav>
    <a href="{% url 'guia_de_hobbies:hobbies_jovens' %}">JOVENS</a>
    </nav>

    <nav>
    <a href="{% url 'guia_de_hobbies:hobbies_idosos' %}">IDOSOS</a>
    </nav>

    <style>
        body {
            background: beige;
            color: black;
        }
    </style>

guia_de_hobbies/templates/hobbies/hobbies_adolescentes.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hobbies para Adolescentes</title>

    <style>
        body {
            background: lightblue;
            color: white;
        }
    </style>
</head>
<body>
    <header>
        <h1>Adolescentes (13-19 anos)</h1>
    </header>

    <main>
        <h2>Puberdade:</h2>
        <p>A fase em que ocorrem mudanças físicas significativas, como o desenvolvimento dos órgãos sexuais, crescimento corporal e mudanças hormonais.</p>

        <h2>Exploração de Identidade:</h2>
        <p>Os adolescentes buscam compreender quem são, seus valores, interesses e objetivos de vida.</p>

        <h2>Sugestões de hobbies:</h2>
        <ul>
            <li><strong>Música (tocar um instrumento):</strong> Aprender a tocar um instrumento musical é uma forma gratificante de expressão criativa e pode ajudar os adolescentes a aliviar o estresse e desenvolver habilidades de concentração.</li>

            <li><strong>Fotografia:</strong> Com o crescimento das redes sociais, a fotografia se tornou um hobby popular entre os adolescentes. Além de capturar momentos especiais, a fotografia promove a criatividade e a apreciação estética.</li>

            <li><strong>Programação de Jogos:</strong> Para adolescentes interessados em tecnologia, aprender a programar jogos pode ser uma atividade empolgante e desafiadora. Isso estimula o pensamento lógico, a resolução de problemas e abre portas para futuras oportunidades de carreira.</li>

            <li><strong>Escrita Criativa:</strong> Escrever contos, poemas ou até mesmo iniciar um blog pessoal permite que os adolescentes explorem sua imaginação e expressem suas ideias e emoções de forma criativa.</li>

            <li><strong>Esportes Radicais:</strong> Praticar esportes radicais como skate, surf, escalada ou snowboard oferece uma dose de adrenalina e aventura, além de promover coragem, determinação e habilidades motoras.</li>
        </ul>
        <p>Quer saber da próxima etapa? Clique <a href="{% url 'guia_de_hobbies:hobbies_jovens' %}">aqui</a>.</p>
    </main>
</body>
</html>

guia_de_hobbies/templates/hobbies/hobbies_criancas.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hobbies para crianças</title>

    <style>
        body {
            background: pink;
            color: white;
        }
    </style>
</head>
<body>
    <header>
        <h1>Crianças (0-12 anos)</h1>
    </header>

    <main>
        <h2>Infância:</h2>
        <p>Os primeiros anos de vida, onde ocorrem marcos importantes como o desenvolvimento da linguagem, coordenação motora e habilidades sociais.</p>

        <h2>Pré-adolescência:</h2>
        <p>O período que antecede a adolescência, caracterizado pelo crescimento físico, desenvolvimento cognitivo e início da formação de identidade.</p>

        <h2>Sugestões de hobbies:</h2>
        <ul>
            <li><strong>Desenho e Pintura:</strong> As crianças adoram expressar sua criatividade através do desenho e da pintura. Este hobby
            ajuda no desenvolvimento da coordenação motora fina e estimula a imaginação.</li>

            <li><strong>Esportes em Equipe:</strong> Participar de esportes como futebol, basquete ou vôlei ajuda as crianças a aprender
            habilidades sociais, trabalho em equipe e disciplina, além de promover um estilo de vida ativo e saudável.</li>

            <li><strong>Leitura de Livros Infantis:</strong> Ler livros infantis é uma maneira maravilhosa de estimular
            a imaginação e desenvolver habilidades linguísticas. Além disso, ajuda as crianças a adquirir o hábito da leitura desde cedo.</li>

            <li><strong>Montagem de Quebra-Cabeças:</strong> Montar quebra-cabeças é um hobby divertido e
            educativo que ajuda as crianças a desenvolver habilidades cognitivas, como resolução de problemas, reconhecimento de padrões e paciência.</li>

            <li><strong>Jardinagem em Miniatura:</strong>  Incentivar as crianças a cuidar de plantas em pequenos jardins é uma ótima maneira de ensiná-las sobre a natureza,
            responsabilidade e apreciação pelo meio ambiente.</li>


        </ul>
        <p>Quer saber da proxima etapa? Click</p>
         <nav>
        <a href="{% url 'guia_de_hobbies:hobbies_adolescentes' %}">aqui</a>
        </nav>

    </main>



</body>
</html>

guia_de_hobbies/templates/hobbies/hobbies_idosos.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hobbies para Idosos</title>

    <style>
        body {
            background: lightgrey;
            color: white;
        }
    </style>
</head>
<body>
    <header>
        <h1>Idosos (40 anos em diante)</h1>
    </header>

    <main>
        <h2>Horticultura:</h2>
        <p>Cultivar um jardim de flores, vegetais ou ervas é uma atividade terapêutica e gratificante para os idosos. Além de fornecer exercício físico leve, a jardinagem promove relaxamento e conexão com a natureza.</p>

        <h2>Dança de Salão:</h2>
        <p>A dança de salão, como salsa, tango ou valsa, é uma forma divertida de se exercitar, socializar e manter a mente ativa. Além disso, melhora a postura, equilíbrio e coordenação motora.</p>

        <h2>Sugestões de hobbies:</h2>
        <ul>
            <li><strong>Pintura e Desenho:</strong> Muitos idosos descobrem talentos artísticos tardios e se dedicam à pintura ou desenho como um hobby relaxante e criativo. Isso permite que expressem sua imaginação e emoções de forma visual.</li>

            <li><strong>Voluntariado:</strong> Muitos idosos encontram satisfação e propósito no voluntariado, seja ajudando em abrigos de animais, hospitais, escolas ou outras organizações comunitárias. Isso promove um senso de contribuição e conexão com a comunidade.</li>

            <li><strong>Leitura e Clube do Livro:</strong> Participar de um clube do livro ou simplesmente dedicar tempo para ler livros é uma atividade prazerosa e intelectualmente estimulante para os idosos. Isso mantém a mente afiada, amplia horizontes e oferece entretenimento.</li>

        </ul>

         <p>Quer saber sobre as etapa? Clique <a href="{% url 'guia_de_hobbies:hobbies' %}">aqui</a>.</p>
    </main>
</body>
</html>

guia_de_hobbies/templates/hobbies/hobbies_jovens.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hobbies para Jovens</title>

    <style>
        body {
            background: lightgreen;
            color: white;
        }
    </style>
</head>
<body>
    <header>
        <h1>Jovens (20-39 anos)</h1>
    </header>

    <main>
        <h2>Estabelecimento de Carreira:</h2>
        <p>Os jovens estão focados em construir suas carreiras, adquirir habilidades profissionais e alcançar estabilidade financeira.</p>

        <h2>Relacionamentos Românticos:</h2>
        <p>Muitos jovens iniciam relacionamentos sérios, casamentos e fundam famílias.</p>

        <h2>Sugestões de hobbies:</h2>
        <ul>
            <li><strong>Culinária Gourmet:</strong> Aprender a cozinhar pratos gourmet é uma forma deliciosa de relaxar e impressionar amigos e familiares. Além disso, é uma habilidade prática que pode trazer muita satisfação pessoal.</li>

            <li><strong>Corrida de Rua:</strong> Participar de corridas de rua, como maratonas ou meias maratonas, é uma excelente maneira de manter a forma física, aliviar o estresse e fazer novas amizades na comunidade de corredores.</li>

            <li><strong>Arte DIY (Faça Você Mesmo):</strong> O movimento DIY está em alta, com muitos jovens explorando atividades artísticas como pintura, escultura, costura, entre outros. Isso permite que expressem sua criatividade de forma única e personalizada.</li>

            <li><strong>Viagens Aventureiras:</strong> Explorar destinos exóticos e realizar viagens de aventura, como trekking em montanhas, mergulho em recifes de corais ou acampamento selvagem, proporciona experiências inesquecíveis e um contato mais profundo com a natureza.</li>

            <li><strong>Yoga e Meditação:</strong> Praticar yoga e meditação é uma maneira eficaz de encontrar equilíbrio e bem-estar em meio ao ritmo acelerado da vida moderna. Essas práticas promovem relaxamento, flexibilidade, concentração e autoconsciência.</li>
        </ul>
        <p>Quer saber da próxima etapa? Clique <a href="{% url 'guia_de_hobbies:hobbies_idosos' %}">aqui</a>.</p>
    </main>
</body>
</html>